server:
  port: 8002

spring:
  application:
    name: msvc-cursos
  datasource:
    url: jdbc:postgresql://localhost:5432/curso-spring-docker-kubernetes
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
