server:
  port: 8001

spring:
  application:
    name: msvc-usuarios
  datasource:
    url: jdbc:postgresql://localhost:5432/curso-spring-docker-kubernetes
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

logging:
  level:
    org.hibernate.SQL: debug
